import {useEffect,useState} from "react";
import {API,authHeaders} from "../api";
function Applications(){
 const [data,setData]=useState(null),[resumes,setResumes]=useState([]),[f,setF]=useState({internshipTitle:"",companyName:"",applicationUrl:"",resumeId:""});
 const load=async()=>{const [r,rr]=await Promise.all([fetch(`${API}/api/applications`,{headers:authHeaders()}),fetch(`${API}/api/resume`,{headers:authHeaders()})]);const d=await r.json(),rd=await rr.json();if(r.ok)setData(d);if(rr.ok)setResumes(rd)};
 useEffect(()=>{load()},[]);
 const submit=async()=>{if(!f.internshipTitle.trim())return alert("Internship title is required.");const r=await fetch(`${API}/api/applications`,{method:"POST",headers:authHeaders(true),body:JSON.stringify({...f,resumeId:f.resumeId||null})});const d=await r.json();if(!r.ok)return alert(d.message);alert(d.message);setF({internshipTitle:"",companyName:"",applicationUrl:"",resumeId:""});load()};
 if(!data)return <div className="card p-4">Loading applications...</div>;const s=data.subscription;
 return <div><h2>Internship Applications 🎓</h2><div className="alert alert-info"><b>{s.plan_name}</b> · Used {s.applications_used||0}/{s.application_limit===null?"Unlimited":s.application_limit}</div><div className="card p-4 mb-4"><h5>Apply / Record Internship</h5><input className="form-control mb-2" placeholder="Internship Title" value={f.internshipTitle} onChange={e=>setF({...f,internshipTitle:e.target.value})}/><input className="form-control mb-2" placeholder="Company Name" value={f.companyName} onChange={e=>setF({...f,companyName:e.target.value})}/><input className="form-control mb-2" placeholder="Application URL" value={f.applicationUrl} onChange={e=>setF({...f,applicationUrl:e.target.value})}/><select className="form-select mb-2" value={f.resumeId} onChange={e=>setF({...f,resumeId:e.target.value})}><option value="">No resume attached</option>{resumes.map(r=><option key={r.id} value={r.id}>{r.title}{r.is_default?" (Default)":""}</option>)}</select><button className="btn btn-primary" onClick={submit}>Submit Application</button></div><div className="card p-3"><h5>Application History</h5>{data.applications.length===0?<p className="text-muted">No applications yet.</p>:data.applications.map(a=><div className="border rounded p-2 mb-2" key={a.id}><b>{a.internship_title}</b> · {a.company_name||"Company not specified"}<small className="d-block text-muted">{new Date(a.applied_at).toLocaleString()} · {a.resume_title?`Resume: ${a.resume_title}`:"No resume"}</small>{a.application_url&&<a href={a.application_url} target="_blank" rel="noreferrer">Open application ↗</a>}</div>)}</div></div>
}
export default Applications;
