import {useEffect,useState} from "react";import {API,authHeaders} from "../api";import {supportedLanguages} from "../i18n";
function Language({onLanguage}){
 const [lang,setLang]=useState("English"),[challenge,setChallenge]=useState(""),[otp,setOtp]=useState(""),[history,setHistory]=useState([]);
 const load=async()=>{try{const r=await fetch(`${API}/api/language`,{headers:authHeaders()});const d=await r.json();if(r.ok)setLang(d.language);const h=await fetch(`${API}/api/language/history`,{headers:authHeaders()});const hd=await h.json();if(h.ok)setHistory(hd)}catch{}};
 useEffect(()=>{load()},[]);
 const choose=async e=>{const v=e.target.value;if(v==="French"){try{const r=await fetch(`${API}/api/language/request-french`,{method:"POST",headers:authHeaders(true),body:"{}"});const d=await r.json();if(!r.ok)throw new Error(d.message);setChallenge(d.challengeId);setLang("French");if(d.demoOtp)setOtp(d.demoOtp);alert(d.demoOtp?`${d.message} Demo OTP: ${d.demoOtp}`:d.message)}catch(x){alert(x.message);e.target.value=lang}}else{try{const r=await fetch(`${API}/api/language`,{method:"PUT",headers:authHeaders(true),body:JSON.stringify({language:v})});const d=await r.json();if(!r.ok)throw new Error(d.message);setLang(v);onLanguage(v)}catch(x){alert(x.message)}}};
 const verify=async()=>{try{const r=await fetch(`${API}/api/language`,{method:"PUT",headers:authHeaders(true),body:JSON.stringify({language:"French",challengeId:challenge,otp})});const d=await r.json();if(!r.ok)throw new Error(d.message);setChallenge("");setOtp("");setLang("French");onLanguage("French");alert(d.message);load()}catch(e){alert(e.message)}};
 return <div className="card p-4 shadow-sm"><h2>Language 🌐</h2><p className="text-muted">Switch instantly. French requires email OTP verification.</p><select className="form-select" value={lang} onChange={choose}>{supportedLanguages.map(x=><option key={x}>{x}</option>)}</select>{challenge&&<div className="mt-3"><input className="form-control mb-2" maxLength="6" placeholder="French OTP" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))}/><button className="btn btn-primary" onClick={verify}>Verify & Enable French</button></div>}<h5 className="mt-4">Language Change History</h5><div className="table-responsive"><table className="table"><thead><tr><th>Language</th><th>Time</th><th>IP</th><th>Browser</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.selected_language}</td><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.ip_address||"Unknown"}</td><td>{x.browser||"Unknown"}</td></tr>)}</tbody></table></div></div>
}
export default Language;
