import {useEffect,useState} from "react";
import {API,authHeaders,token} from "../api";

function loadRazorpay(){return new Promise(resolve=>{if(window.Razorpay)return resolve(true);const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)})}
const fields=[["fullName","Full Name"],["email","Email"],["phone","Phone"],["careerObjective","Career Objective"],["education","Education"],["skills","Skills"],["workExperience","Work Experience"],["internships","Internships"],["projects","Projects"],["certifications","Certifications"],["achievements","Achievements"],["languages","Languages"],["socialLinks","Social Links"],["references","References"]];
const templates=["ATS Template 1","ATS Template 2","ATS Template 3","ATS Template 4","ATS Template 5"];
function ResumeBuilder(){
 const [form,setForm]=useState({title:"",template:"ATS Template 1",color:"#1d4ed8",font:"Helvetica",...Object.fromEntries(fields.map(x=>[x[0],""]))});
 const [photo,setPhoto]=useState(null),[challenge,setChallenge]=useState(""),[otp,setOtp]=useState(""),[verified,setVerified]=useState(false),[resumes,setResumes]=useState([]),[plan,setPlan]=useState("Loading..."),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false);
 const set=(k,v)=>setForm({...form,[k]:v});
 const load=async()=>{try{const [rr,sr]=await Promise.all([fetch(`${API}/api/resume`,{headers:authHeaders()}),fetch(`${API}/api/subscription`,{headers:authHeaders()})]);const rd=await rr.json(),sd=await sr.json();if(rr.ok)setResumes(rd);if(sr.ok)setPlan(sd.subscription?.plan_name||"Free")}catch{setPlan("Unknown")}};
 useEffect(()=>{load()},[]);
 const sendOtp=async()=>{setBusy(true);try{const r=await fetch(`${API}/api/resume/otp`,{method:"POST",headers:authHeaders(true),body:"{}"});const d=await r.json();if(!r.ok)throw new Error(d.message);setChallenge(d.challengeId);if(d.demoOtp)setOtp(d.demoOtp);alert(d.demoOtp?`${d.message} Demo OTP: ${d.demoOtp}`:d.message)}catch(e){alert(e.message)}finally{setBusy(false)}};
 const verify=async()=>{setBusy(true);try{const r=await fetch(`${API}/api/resume/verify-otp`,{method:"POST",headers:authHeaders(true),body:JSON.stringify({challengeId:challenge,otp})});const d=await r.json();if(!r.ok)throw new Error(d.message);setVerified(true);alert(d.message)}catch(e){alert(e.message)}finally{setBusy(false)}};
 const generate=async()=>{if(!verified)return alert("Verify email OTP first.");if(!form.title||!form.fullName||!form.email)return alert("Resume title, name and email are required.");setBusy(true);try{const r=await fetch(`${API}/api/resume/order`,{method:"POST",headers:authHeaders(true),body:JSON.stringify({challengeId:challenge})});const o=await r.json();if(!r.ok)throw new Error(o.message);if(o.mock){return finish({orderId:o.orderId})}const ok=await loadRazorpay();if(!ok)throw new Error("Razorpay checkout could not load.");new window.Razorpay({key:o.keyId,amount:o.amount,currency:"INR",name:"Internship Platform",description:"Resume generation",order_id:o.orderId,handler:response=>finish({...response,orderId:o.orderId})}).open()}catch(e){alert(e.message);setBusy(false)}};
 const finish=async(pay)=>{try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));fd.append("challengeId",challenge);Object.entries(pay).forEach(([k,v])=>fd.append(k,v||""));if(photo)fd.append("photo",photo);const r=await fetch(`${API}/api/resume/generate`,{method:"POST",headers:{Authorization:`Bearer ${token()}`},body:fd});const d=await r.json();if(!r.ok)throw new Error(d.message);alert(`${d.message} Invoice: ${d.invoice}`);setVerified(false);setChallenge("");setOtp("");setPreview(false);load()}catch(e){alert(e.message)}finally{setBusy(false)}};
 const download=async r=>{try{const rr=await fetch(`${API}/api/resume/${r.id}/download`,{method:"POST",headers:authHeaders()});const d=await rr.json();if(!rr.ok)throw new Error(d.message);window.open(`${API}${d.url}`,"_blank","noopener,noreferrer")}catch(e){alert(e.message)}};
 const paid=["bronze","silver","gold"].includes(plan.toLowerCase());
 return <div>
  <div className="card p-4 shadow-sm"><div className="d-flex justify-content-between align-items-start gap-2 flex-wrap"><div><h2>Premium Resume Builder 📄</h2><p className="text-muted mb-1">Current subscription: <b>{plan}</b></p><p className="text-muted">Premium users can generate a PDF for ₹50 per generation/download. Email OTP is required before payment.</p></div><span className={`badge ${paid?"text-bg-success":"text-bg-secondary"}`}>{paid?"Premium access":"Premium required"}</span></div>
   {!paid&&<div className="alert alert-warning mt-3">Upgrade to Bronze, Silver or Gold on the Subscription page before generating a resume.</div>}
   <div className="row g-2">{<div className="col-12"><input className="form-control" placeholder="Resume Title" value={form.title} onChange={e=>set("title",e.target.value)}/></div>}{fields.map(([k,p])=><div className="col-md-6" key={k}><input className="form-control" placeholder={p} value={form[k]} onChange={e=>set(k,e.target.value)}/></div>)}</div>
   <div className="row g-2 mt-1"><div className="col-md-4"><select className="form-select" value={form.template} onChange={e=>set("template",e.target.value)}>{templates.map(t=><option key={t}>{t}</option>)}</select></div><div className="col-md-4"><select className="form-select" value={form.font} onChange={e=>set("font",e.target.value)}><option>Helvetica</option><option>Times-Roman</option><option>Courier</option></select></div><div className="col-md-4"><input className="form-control" type="color" value={form.color} onChange={e=>set("color",e.target.value)}/></div></div>
   <input className="form-control mt-2" type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0]||null)}/>
   <button className="btn btn-outline-secondary mt-3" onClick={()=>setPreview(!preview)}>{preview?"Hide Preview":"Preview Resume"}</button>
   {preview&&<div className="border rounded p-4 mt-3 bg-white"><h3 style={{color:form.color,fontFamily:form.font}}>{form.fullName||"Your Name"}</h3><p>{form.email}{form.phone?` · ${form.phone}`:""}</p>{[["Career Objective",form.careerObjective],["Education",form.education],["Skills",form.skills],["Work Experience",form.workExperience],["Internships",form.internships],["Projects",form.projects],["Certifications",form.certifications],["Achievements",form.achievements],["Languages",form.languages],["Social Links",form.socialLinks],["References",form.references]].filter(x=>x[1]).map(x=><section key={x[0]} className="mt-3"><h6 style={{color:form.color}}>{x[0]}</h6><div style={{whiteSpace:"pre-wrap"}}>{x[1]}</div></section>)}</div>}
   {paid&&(!challenge?<button className="btn btn-primary mt-3" disabled={busy} onClick={sendOtp}>Verify Email OTP</button>:!verified?<div className="mt-3"><input className="form-control mb-2" maxLength="6" inputMode="numeric" placeholder="Enter OTP" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))}/><button className="btn btn-primary" disabled={busy} onClick={verify}>Verify OTP</button></div>:<button className="btn btn-success mt-3" disabled={busy} onClick={generate}>{busy?"Processing...":"Pay ₹50 & Generate PDF"}</button>)}
  </div>
  <div className="card p-3 mt-4"><h5>Saved Resume Versions & Download History</h5>{resumes.length===0?<p className="text-muted">No generated resumes yet.</p>:resumes.map(r=><div className="border rounded p-2 mb-2 d-flex justify-content-between align-items-center gap-2 flex-wrap" key={r.id}><span><b>{r.title}</b> · {r.template} {r.is_default&&<span className="badge text-bg-success ms-2">Default</span>}</span><div>{!r.is_default&&<button className="btn btn-sm btn-outline-secondary me-2" onClick={async()=>{const rr=await fetch(`${API}/api/resume/${r.id}/default`,{method:"POST",headers:authHeaders()});const dd=await rr.json();alert(dd.message);load()}}>Set default</button>}{r.pdf_url&&<button className="btn btn-sm btn-outline-primary" onClick={()=>download(r)}>Download / Open PDF</button>}</div></div>)}</div>
 </div>;
}
export default ResumeBuilder;
