import {useEffect,useState} from "react";import {API,authHeaders} from "../api";
function loadRazorpay(){return new Promise(resolve=>{if(window.Razorpay)return resolve(true);const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)})}
function Subscription(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false);
 const plans=[["Free",0,1],["Bronze",100,3],["Silver",300,5],["Gold",1000,null]];
 const load=async()=>{try{const r=await fetch(`${API}/api/subscription`,{headers:authHeaders()});const d=await r.json();if(r.ok)setData(d)}catch(e){alert("Please login first.")}};
 useEffect(()=>{load()},[]);
 const select=async plan=>{if(plan==="Free"){activate("Free",{});return}setBusy(true);try{const r=await fetch(`${API}/api/subscription/order`,{method:"POST",headers:authHeaders(true),body:JSON.stringify({plan})});const o=await r.json();if(!r.ok)throw new Error(o.message);if(o.mock){activate(plan,{orderId:o.orderId});return}const ok=await loadRazorpay();if(!ok)throw new Error("Razorpay checkout could not load.");new window.Razorpay({key:o.keyId,amount:o.amount,currency:"INR",name:"Internship Platform",description:`${plan} subscription`,order_id:o.orderId,handler:async response=>activate(plan,{...response,orderId:o.orderId}),theme:{color:"#2563eb"}}).open()}catch(e){alert(e.message);setBusy(false)}};
 const activate=async(plan,pay)=>{try{const r=await fetch(`${API}/api/subscription/activate`,{method:"POST",headers:authHeaders(true),body:JSON.stringify({plan,...pay})});const d=await r.json();if(!r.ok)throw new Error(d.message);alert(d.message);load()}catch(e){alert(e.message)}finally{setBusy(false)}};
 if(!data)return <div className="card p-4">Loading subscription...</div>;const s=data.subscription;
 return <div><h2>Subscription Plans 💳</h2><div className="alert alert-info"><b>Current:</b> {s.plan_name} · Used: {s.applications_used||0} / {s.application_limit===null?"Unlimited":s.application_limit} applications {s.renewal_date&&`· Renews ${new Date(s.renewal_date).toLocaleDateString()}`}</div><div className="row">{plans.map(([name,amount,limit])=><div className="col-md-3 mb-3" key={name}><div className={`card h-100 p-3 ${s.plan_name===name?"border-primary border-2":""}`}><h4>{name}</h4><h5>₹{amount}/month</h5><p>{limit===null?"Unlimited applications":`${limit} applications/month`}</p><button className="btn btn-primary" disabled={busy} onClick={()=>select(name)}>{s.plan_name===name?(name==="Free"?"Current Plan":"Renew"):"Purchase / Upgrade"}</button></div></div>)}</div><div className="alert alert-warning">Payment window: <b>5:00 AM – 11:45 AM IST</b>. Razorpay Test Mode is supported; local demo mode is available when configured.</div><button className="btn btn-outline-danger" onClick={async()=>{const r=await fetch(`${API}/api/subscription/cancel`,{method:"POST",headers:authHeaders()});const d=await r.json();alert(d.message);load()}}>Cancel subscription</button><h5 className="mt-4">Subscription History</h5><div className="table-responsive"><table className="table"><thead><tr><th>Plan</th><th>Amount</th><th>Status</th><th>Renewal</th></tr></thead><tbody>{data.history.map(x=><tr key={x.id}><td>{x.plan_name}</td><td>₹{x.amount}</td><td>{x.status}</td><td>{x.renewal_date?new Date(x.renewal_date).toLocaleDateString():"—"}</td></tr>)}</tbody></table></div><h5 className="mt-4">Payment / Invoice History</h5><div className="table-responsive"><table className="table"><thead><tr><th>Invoice</th><th>Plan</th><th>Amount</th><th>Transaction</th><th>Status</th></tr></thead><tbody>{data.payments.map(x=><tr key={x.id}><td>{x.invoice_number||"—"}</td><td>{x.plan_name}</td><td>₹{x.amount}</td><td>{x.transaction_id||"—"}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>
}
export default Subscription;
